/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
/**
 *
 * @author ariwira
 */
public class PanelKiriOrder extends javax.swing.JPanel {
    PanelIsi content = new PanelIsi();
    /**
     * Creates new form PanelKiriOrder
     */
      
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon bg = new ImageIcon(new ImageIcon("Assets/left.jpg").getImage().getScaledInstance(90, 520, Image.SCALE_DEFAULT));
        bg.paintIcon(this, g, 0, 0);
    }
    public void addIcon(){
        ImageIcon MejaMerah=new ImageIcon(new ImageIcon("Assets/table1U.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
        ImageIcon MejaHijau=new ImageIcon(new ImageIcon("Assets/table1A.png").getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
        JLabel MejaMerahIcon = new JLabel(MejaMerah);
        JLabel MejaHijauIcon = new JLabel(MejaHijau);
        
        MejaHijauIcon.setSize(60, 60);
        MejaHijauIcon.setLocation(10, 100);
        MejaMerahIcon.setSize(60, 60);
        MejaMerahIcon.setLocation(10, 200);
        
        add(MejaHijauIcon);
        add(MejaMerahIcon);
        
    }
    public PanelKiriOrder() {
        initComponents();
        addIcon();
        setSize(80,600);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
