/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author ariwira
 */
public class PanelKiri extends javax.swing.JPanel implements MouseListener{
    private int button_height= 60,button_width=60;
    public static int triggerButton = 1,tableTypeTrigger=0,triggerDelete=0;
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon background = new ImageIcon(new ImageIcon("Assets/left.jpg").getImage().getScaledInstance(80, 800, Image.SCALE_DEFAULT));
        background.paintIcon(this, g, 0, 0);
        //System.out.println("gambar");
    }
   
    /**
     * Creates new form PanelKiri
     */
    public void addButton(){
        ImageIcon MejaKotak=new ImageIcon(new ImageIcon("Assets/table1.jpg").getImage().getScaledInstance(button_height, button_width, Image.SCALE_DEFAULT));
        ImageIcon MejaBulat=new ImageIcon(new ImageIcon("Assets/table2.png").getImage().getScaledInstance(button_height, button_width, Image.SCALE_DEFAULT));
        final ImageIcon add=new ImageIcon(new ImageIcon("Assets/add.png").getImage().getScaledInstance(button_height, button_width, Image.SCALE_DEFAULT));
        final ImageIcon addSelected=new ImageIcon(new ImageIcon("Assets/addpicked.png").getImage().getScaledInstance(button_height, button_width, Image.SCALE_DEFAULT));
        final ImageIcon delete=new ImageIcon(new ImageIcon("Assets/delete.png").getImage().getScaledInstance(button_height, button_width, Image.SCALE_DEFAULT));
        final ImageIcon deleteSelected=new ImageIcon(new ImageIcon("Assets/deletepicked.png").getImage().getScaledInstance(button_height, button_width, Image.SCALE_DEFAULT));
        
        
        JLabel mejaKotakButt=new JLabel(MejaKotak);
        JLabel mejaBulatButt=new JLabel(MejaBulat);
        final JLabel buttonAdd=new JLabel(add);
        final JLabel buttonDelete=new JLabel(delete);
        
        
        
        mejaKotakButt.setSize(button_height, button_width);
        mejaKotakButt.setLocation(10, 50);
        
        mejaBulatButt.setSize(button_height, button_width);
        mejaBulatButt.setLocation(10, 150);
        
        buttonAdd.setSize(button_height, button_width);
        buttonAdd.setLocation(10, 250);

        buttonDelete.setSize(button_height, button_width);
        buttonDelete.setLocation(10, 350);
        
        buttonAdd.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
               if(triggerButton==1){
                    buttonAdd.setIcon(addSelected);
                    //buttonDelete.setIcon(delete);
                    triggerButton=2;    
               }else if(triggerButton==2){
                   buttonAdd.setIcon(add);
                   //buttonDelete.setIcon(deleteSelected);
                   triggerButton=1;
               }
            }
        });
        buttonDelete.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                if(triggerButton==1){
                    buttonDelete.setIcon(deleteSelected);
                    triggerButton=2;
                    triggerDelete=1;
                    
                }else{
                    buttonDelete.setIcon(delete);
                    triggerButton=1;
//                    triggerDelete=0;
                }
                
            }
        });
        
        mejaKotakButt.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                if(triggerButton==2){
                    tableTypeTrigger=1;
                }
                
            }
        });
        
        mejaBulatButt.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                if(triggerButton==2){
                    tableTypeTrigger=2;
                }
            }
        });
        add(mejaKotakButt);
        add(mejaBulatButt);
        
        add(buttonAdd);
        add(buttonDelete);
        
       
    }
    
    public PanelKiri() {
        initComponents();
        //PanelKiri.setLayout(new java.awt.FlowLayout());
        addButton();
        setSize(80,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }
}
