/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.BorderLayout;
import java.awt.Component;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.*;
import javax.net.ssl.ManagerFactoryParameters;
/**
 *
 * @author ariwira
 */
public class vidPanel extends javax.swing.JPanel {

    /**
     * Creates new form vidPanel
     */
    public vidPanel(URL url) {
        Manager.setHint(Manager.LIGHTWEIGHT_RENDERER, true);
        Player mediaPlayer;
        try {
            mediaPlayer = Manager.createRealizedPlayer(url);
            Component video = mediaPlayer.getVisualComponent();
            //Component control = mediaPlayer.getControlPanelComponent();
            add(video,BorderLayout.CENTER);
            mediaPlayer.start();
        } catch (IOException ex) {
            System.out.println("ga bs baca file");
            //Logger.getLogger(vidPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoPlayerException ex) {
            System.out.println("ga ada player yg cocok");
            //Logger.getLogger(vidPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CannotRealizeException ex) {
            System.out.println("Manager ga kenal resource");
            //Logger.getLogger(vidPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
